#!/usr/bin/env python3
"""Generate README.md (qiyuangong/leetcode style) from LeetSync folders."""
import json, os, re, sys, time, urllib.error, urllib.request
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
META = ROOT / "meta.json"          # cache title/difficulty lay tu LeetCode
IDEAS = ROOT / "ideas.json"        # cache: {"1-two-sum": "Hash map, O(n) and O(n)"} - sua tay thoai mai
START, END = "<!-- PROBLEMS:START -->", "<!-- PROBLEMS:END -->"
MODEL = os.environ.get("GEMINI_MODEL", "gemini-3.8-flash")
MAX_AI_PER_RUN = int(os.environ.get("MAX_AI_PER_RUN", "40"))   # gioi han so lan goi AI moi lan chay
AI_SLEEP = float(os.environ.get("AI_SLEEP", "4"))              # nghi giua cac lan goi (tranh 429)
AI_OFF = False                                                  # tu tat AI neu loi vinh vien (404/401/403)
LANGS = {".java": "Java", ".py": "Python", ".cpp": "C++", ".c": "C", ".cs": "C#", ".js": "JavaScript",
         ".ts": "TypeScript", ".sql": "SQL", ".go": "Go", ".kt": "Kotlin", ".rs": "Rust", ".swift": "Swift",
         ".rb": "Ruby", ".php": "PHP", ".sh": "Bash"}

HEADER = """# LeetCode Solutions

This repository contains my solutions to LeetCode problems.
Solutions are synced from LeetCode with [LeetSync](https://github.com/LeetSync/LeetSync) and this README is generated by GitHub Actions.

{stats}

## Problems & Solutions

"""


def parse_problem(d: Path):
    num, slug = d.name.split("-", 1)
    title = slug.replace("-", " ").title()
    link = f"https://leetcode.com/problems/{slug}/"
    diff, got_title = "", False
    rd = d / "README.md"
    if rd.exists():
        t = rd.read_text(encoding="utf-8", errors="ignore")
        m = (re.search(r'<a href="(https://leetcode\.com/problems/[^"]+)">\s*\d+\.\s*(.+?)\s*</a>', t)
             or re.search(r'\[\s*\d+\.\s*(.+?)\s*\]\((https://leetcode\.com/problems/[^)]+)\)', t))
        if m:
            a, b = m.group(1), m.group(2)
            link, title = (a, b) if a.startswith("http") else (b, a)
            got_title = True
        m = re.search(r"\b(Easy|Medium|Hard)\b", t[:2000])
        if m:
            diff = m.group(1)
    sols = [(LANGS[f.suffix.lower()], f) for f in sorted(d.iterdir()) if f.suffix.lower() in LANGS]
    return int(num), d.name, title, link, diff, sols, got_title, slug


def fetch_lc(slug: str) -> dict:
    q = {"query": "query q($s:String!){question(titleSlug:$s){title difficulty}}", "variables": {"s": slug}}
    req = urllib.request.Request("https://leetcode.com/graphql", data=json.dumps(q).encode(), headers={
        "content-type": "application/json", "referer": "https://leetcode.com/problems/" + slug + "/",
        "user-agent": "Mozilla/5.0"})
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            qq = json.load(r)["data"]["question"]
        return {"title": qq["title"], "difficulty": qq["difficulty"]}
    except Exception as e:
        print(f"[warn] leetcode meta failed for {slug}: {e}", file=sys.stderr)
        return {}


def ask_idea(code: str, title: str) -> str:
    """Return a one-line approach summary, or '' on failure."""
    global AI_OFF
    key = os.environ.get("GEMINI_API_KEY", "").strip()   # strip: secret paste thua \n se lam hong header
    if not key or AI_OFF:
        return ""
    prompt = (f"LeetCode problem: {title}\n\nSolution:\n{code[:6000]}\n\n"
              "Write ONE short line (max 25 words) in English describing the approach and its complexity, "
              "like: 'Hash map, O(n) and O(n)'. Output only that line.")
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{MODEL}:generateContent"
    body = json.dumps({"contents": [{"parts": [{"text": prompt}]}]}).encode()
    headers = {"x-goog-api-key": key, "content-type": "application/json"}

    for attempt in range(3):
        req = urllib.request.Request(url, data=body, headers=headers)
        try:
            with urllib.request.urlopen(req, timeout=60) as r:
                data = json.load(r)
            parts = data["candidates"][0]["content"]["parts"]
            text = "".join(p.get("text", "") for p in parts)
            return " ".join(text.split())
        except urllib.error.HTTPError as e:
            detail = e.read().decode(errors="ignore")[:300]
            if e.code in (429, 500, 503) and attempt < 2:      # tam thoi -> doi roi thu lai
                time.sleep(15 * (attempt + 1))
                continue
            if e.code in (400, 401, 403, 404):                 # sai key/model -> khoi goi tiep
                AI_OFF = True
                print(f"[error] Gemini disabled for this run (model={MODEL}): HTTP {e.code} {detail}",
                      file=sys.stderr)
            else:
                print(f"[warn] AI failed for {title}: HTTP {e.code} {detail}", file=sys.stderr)
            return ""
        except Exception as e:
            print(f"[warn] AI failed for {title}: {e}", file=sys.stderr)
            return ""
    return ""


def main():
    ideas = json.loads(IDEAS.read_text(encoding="utf-8")) if IDEAS.exists() else {}
    meta = json.loads(META.read_text(encoding="utf-8")) if META.exists() else {}
    probs = sorted(parse_problem(d) for d in ROOT.iterdir()
                   if d.is_dir() and re.match(r"^\d+-.+", d.name))

    rows = []
    counts = {"Easy": 0, "Medium": 0, "Hard": 0}
    ai_calls = 0
    for num, name, title, link, diff, sols, got_title, slug in probs:
        if (not diff or not got_title) and name not in meta:
            m = fetch_lc(slug)
            if m:
                meta[name] = m
        m = meta.get(name, {})
        diff = diff or m.get("difficulty", "")
        if not got_title and m.get("title"):
            title = m["title"]
        if diff in counts:
            counts[diff] += 1
        if not ideas.get(name) and sols and not AI_OFF and ai_calls < MAX_AI_PER_RUN:
            idea = ask_idea(sols[0][1].read_text(encoding="utf-8", errors="ignore"), title)
            ai_calls += 1
            if idea:
                ideas[name] = idea
            time.sleep(AI_SLEEP)
        sol_md = " ".join(f"[{lang}]({quote(name)}/{quote(f.name)})" for lang, f in sols) or "-"
        idea = ideas.get(name, "-").replace("|", "\\|")
        rows.append(f"| {num} | [{title}]({link}) | {sol_md} | {diff or '-'} | {idea} |")

    stats = (f"**Solved: {len(probs)}** &nbsp;|&nbsp; Easy: {counts['Easy']} &nbsp;|&nbsp; "
             f"Medium: {counts['Medium']} &nbsp;|&nbsp; Hard: {counts['Hard']}")
    table = "| # | Title | Solution | Difficulty | Basic idea (One line) |\n| --- | --- | --- | --- | --- |\n"
    table += "\n".join(rows)
    block = f"{START}\n{table}\n{END}"

    old = README.read_text(encoding="utf-8") if README.exists() else ""
    if START in old and END in old:
        new = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block, old, flags=re.S)
        new = re.sub(r"\*\*Solved: .*?\n", lambda _: stats + "\n", new, count=1)
    else:
        new = HEADER.format(stats=stats) + block + "\n"
    README.write_text(new, encoding="utf-8")
    META.write_text(json.dumps(meta, indent=2, ensure_ascii=False, sort_keys=True), encoding="utf-8")
    IDEAS.write_text(json.dumps(ideas, indent=2, ensure_ascii=False, sort_keys=True), encoding="utf-8")
    print(f"{len(probs)} problems, {ai_calls} AI calls, {sum(1 for p in probs if ideas.get(p[1]))} ideas filled")


if __name__ == "__main__":
    main()
